### ISSUE TITLE
Divide current readme into separate tutorials/guides

### ISSUE THREAD

**Issue by ssavvides** [DavideTrupia/Nitro-Spark#1]
I think we should extract guides/tutorials from the README.md file to separate markdown files, and we can link those guides to the top-level README.md.

We should therefore create a directory called `docs` within which we should have:

- `spark-docker.md`: setting up and using a Spark cluster running inside Docker containers
- `spark-docker-ec2.md`: running Spark cluster inside Docker containers on multiple EC2 instances
- `spark-glossary.md`: Spark Glossary
- `docker-glossary.md`: Docker Glossary + most common commands/options
- `aws-glossary.md`: AWS Glossary
- `benchmarking.md`: Info on benchmarks we use

**Comment by DavideTrupia** [comment]
@ssavvides Can you add linking to docs/ from README?

**Comment by ssavvides** [comment]
#11
