### ISSUE TITLE
Cluster file system 

### ISSUE THREAD

**Issue by DavideTrupia** [DavideTrupia/Nitro-Spark#12]
I've seen online a workaround to hdfs cluster, that is not very trivial to setup, and is using **Docker volumes**. 

What if we create another Dockerfile for data called **DockerfileData** that contains `VOLUME="/data"`. 

This way every time we call `docker run ...` we can just add the flag `--volumes-from` and it will **mount** to that container and so have this shared file system. 
![image](https://user-images.githubusercontent.com/43402963/171003863-6c666dff-48a6-4183-a0ab-4e216136d303.png)
This image is taken from docker official docs. 

Instead of uploading to hdfs we just save into `/data` directly.

https://github.com/brunocfnba/docker-spark-cluster

**Comment by DavideTrupia** [comment]
Not possible. Docker volumes are strictly linked to docker containers and the idea works best in local only.

**Comment by ssavvides** [comment]
You can create an image from a running instance if you want. Plus you don't have to terminate your instances. Just stop them and restart them.
