### ISSUE TITLE
Run TPC-H in EC2, no NitroEnclave

### ISSUE THREAD

**Issue by ssavvides** [DavideTrupia/Nitro-Spark#5]
Run all 22 queries of TPC-H in a cluster using "regular" (non-NitroEnclaves) EC2 instances. We should use the same instance type/size that we will be using for NitroEnclaves.

Cluster size and input data size are to be discussed with @Patrick and @shamiek.

I believe that a 3-node cluster and 10GB of input data should suffice to start with.

**Comment by ssavvides** [comment]
Let's focus on getting **2.** by this Friday if at all possible.

We essentially need:

1. A 3-node cluster running HDFS
2. The same 3-node cluster running Spark in docker images
3. Execute the TPC-H benchmark

**Comment by DavideTrupia** [comment]
#16
